spring:
  profiles:
    active: "backup"
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: info
