events-service:
  flows:
    backup:
      storage:
        connection-string: " ??? "
        container-name: events

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
