events-service:
  flows:
    backup:
      storage:
        connection-string: "DefaultEndpointsProtocol=https;AccountName=codehuntersevents;AccountKey=/kRK6umic9IEpPya4x9FLmthOhSyNxefGoo6kukWzqOfBUcKDGdfdt20PEFZysutdcHTJ2RkuoOn+ASt3Ka/tg==;EndpointSuffix=core.windows.net"
        account-name: codehuntersevents
        container-name: events