version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - /Users/czirjak/Desktop/projects/virgo-aws-events-service/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - '9091:3000'
    networks:
      - monitoring
networks:
  monitoring: { }