prometheus:
  prometheusSpec:
    enableAdminAPI: true

grafana:
  enabled: true
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider:
        foldersFromFilesStructure: true

alertmanager:
  enabled: enabled