prometheus:
  prometheusSpec:
    enableAdminAPI: true

grafana:
  enabled: true
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider:
        foldersFromFilesStructure: true
  additionalDataSources:
    - access: proxy
      isDefault: false
      name: loki
      orgId: 1
      type: loki
      url: http://loki:3100/
      version: 1

alertmanager:
  enabled: enabled