apiVersion: v1
kind: Service
metadata:
  name: service-events-service
  namespace: codehunters
spec:
  selector:
    app: events-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP