apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-events-service
  namespace: ???
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    -  http:
         paths:
           - path: ??? service path ???
             pathType: Prefix
             backend:
               service:
                 name: service-events-service
                 port:
                    number: 8080
           - path: ??? health path ???
             pathType: Prefix
             backend:
               service:
                 name: service-events-service
                 port:
                    number: 8080
